name: DevOpsFa1-sampleCode

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo this is just some sample code 

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Install dependencies
        run: |
          # Add commands to install dependencies, e.g., npm install or pip install
          echo Installing dependencies...

      - name: Run tests
        run: |
          # Add commands to run your tests, e.g., npm test or pytest
          echo Running tests...
