name: DevOpsFa1-sampleCode

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Single print to the console
        run: echo this is just some sample code 


      - name: tests would go here
        run: |
          echo Running tests...
          echo please can we be taught how to do this before being asked to do it in a formative. 
          
        
